# Generated by Django 6.1.1 on 2026-09-24 08:54

import frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_whatsapp', models.URLField(blank=True, help_text='Número de atendimento. Ex.: https://wa.me/5511999999999', validators=[frontend.models.validate_whatsapp], verbose_name='WhatsApp do suporte')),
                ('support_telegram', models.URLField(blank=True, help_text='Usuário ou número de atendimento. Ex.: https://t.me/usuario_suporte', validators=[frontend.models.validate_telegram], verbose_name='Telegram do suporte')),
                ('community_whatsapp', models.URLField(blank=True, help_text='Grupo ou canal para os leads entrarem. Ex.: https://chat.whatsapp.com/CODIGO', validators=[frontend.models.validate_whatsapp], verbose_name='Comunidade no WhatsApp')),
                ('community_telegram', models.URLField(blank=True, help_text='Grupo ou canal para os leads entrarem. Ex.: https://t.me/+CODIGO', validators=[frontend.models.validate_telegram], verbose_name='Comunidade no Telegram')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Links de atendimento e comunidade',
                'verbose_name_plural': 'Links de atendimento e comunidade',
            },
        ),
    ]
