# Generated by Django 6.1.1 on 2026-09-25 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VipCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('amount_cents', models.PositiveIntegerField(default=4790)),
                ('br_code', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_charges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cobrança VIP',
                'verbose_name_plural': 'Cobranças VIP',
                'ordering': ['-created_at'],
            },
        ),
    ]
