# Generated by Django 6.1.1 on 2026-09-30 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_userprofile_depositcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='community_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
