# Generated by Django 6.1.1 on 2026-09-25 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoWithdrawBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_withdraw', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'saldo de demonstração',
                'verbose_name_plural': 'saldos de demonstração',
            },
        ),
    ]
